default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0

    hooks:
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7

    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  - repo: local

    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=79, --target-version=py314]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py314-plus]

      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--py314-plus]
